# Generated by Django 4.1.3 on 2022-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images'),
        ),
    ]
