# Generated by Django 4.1.3 on 2022-12-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
    ]
