# Generated by Django 4.1.3 on 2022-12-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_slider_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='color',
        ),
    ]
